### ISSUE TITLE
Come up with the name for our app.

### ISSUE THREAD

**Issue by ha-anna** [chingu-voyages/v40-toucans-team-10#24]
**__Task Description__**
It would be good if every person proposed at least one name.

**__Technical Considerations__**
Something catchy and unique would be good.

**__Additional Considerations__**
It would be better to establish it earlier than later since it's a creative process that takes time.

**Comment by ha-anna** [comment]
For now I have:
- notki (a cute polish word for notes)

**Comment by genelorenzSarmiento0408** [comment]
Mine is Notescri (since `notki` is taken)

**Comment by sukyungdev** [comment]
I thought of Markdown grammar
`[Note](me)`

**Comment by ha-anna** [comment]
@sukyungdev the longer I consider your proposition the more I like it!
I haven't come up with any great ideas, what about you @genelorenzSarmiento0408 ?

**Comment by genelorenzSarmiento0408** [comment]
I like the idea of sukyung! (or in website noteme) https://ph.godaddy.com/domainsearch/find?checkAvail=1&domainToCheck=noteme.dev

**Comment by ha-anna** [comment]
Awesome! Then let's use `[Note](me)`!  @sukyungdev @genelorenzSarmiento0408

**Comment by genelorenzSarmiento0408** [comment]
Or note.me, I haven't added it in my comment

**Comment by ha-anna** [comment]
Name accepted and implemented!
