### ISSUE TITLE
Homepage: The "add" image is not showing

### ISSUE THREAD

**Issue by genelorenzSarmiento0408** [chingu-voyages/v40-toucans-team-10#37]
**Describe the problem**
The "add" image is not showing

**Actual behavior**
I deployed the website to production, and then I saw that the "add" image on the homepage is not showing

**Expected behavior**
The app should show the "add" image 

**To Reproduce**
1. Go to https://fork-v40-toucans-team-10.vercel.app/
2. See an error

**Screenshot**
![image](https://user-images.githubusercontent.com/69145401/187833246-6cf39f09-eea2-4fe1-bedc-cb7b8983803b.png)

**Comment by sukyungdev** [comment]
I don't see it either.
But when I run project in local, I can see icon.

**Comment by ha-anna** [comment]
I changed it svg according to Sukyung's recommendation in the chat. :)
