### ISSUE TITLE
Review info.html and add more personal links/information

### ISSUE THREAD

**Issue by ha-anna** [chingu-voyages/v40-toucans-team-10#40]
It would be good to review the info and change/improve it depending on your preferences.
I included us in alphabetical order.

Also to consider:
- adding our surnames
- adding icons of our choice

![Screen Shot 2022-09-02 at 1 48 30 AM](https://user-images.githubusercontent.com/83631167/188030919-3c654cd6-71fc-4ccf-b057-fc1bc478a77c.png)

**Comment by genelorenzSarmiento0408** [comment]
ok.
