### ISSUE TITLE
Theme no. 4 not showing text

### ISSUE THREAD

**Issue by genelorenzSarmiento0408** [chingu-voyages/v40-toucans-team-10#41]
**Describe the problem**
Theme no. 4 on the website is not displaying text

**Expected behavior**
The themes should display the text

**To Reproduce**
1. Go to the website
2. Click on 'set theme as default' on theme no. 4
3. See an error

**Screenshot**
![image](https://user-images.githubusercontent.com/69145401/188033601-4aa48130-c03b-48f7-bc7f-5a4570d19ae8.png)

**Comment by sukyungdev** [comment]
This is because of the color of the font.

**Comment by genelorenzSarmiento0408** [comment]
Yeah, I already fixed it as per my recent PR (#42)

**Comment by ha-anna** [comment]
SInce it's solved, I'll close the issue :)
