### ISSUE TITLE
"Cannot set properties of null (setting 'value)" error

### ISSUE THREAD

**Issue by genelorenzSarmiento0408** [chingu-voyages/v40-toucans-team-10#46]
**Describe the problem**
There is a "properties of null" issue in the JS

**Expected behavior**
No errors

**To Reproduce**
1. Go to 'theme.html'
2. Click on 'Set theme as default' to any themes
3. See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/69145401/188252326-88363c9a-2255-4daf-8ba5-fa04fd833d22.png)

**Comment by genelorenzSarmiento0408** [comment]
That's why TS is sooo important lol

**Comment by sukyungdev** [comment]
It's okay in my environment. How about now?
<img width="500" alt="스크린샷 2022-09-03 오후 6 40 31" src="https://user-images.githubusercontent.com/96860670/188265114-6fa1cbe6-2bdc-48c5-b5c3-489bd5f6f132.png">

**Comment by genelorenzSarmiento0408** [comment]
Fixed in prod! Closing

**Comment by genelorenzSarmiento0408** [comment]
When creating the note the error occured again
![image](https://user-images.githubusercontent.com/69145401/188339780-21ef8619-c48c-4672-9817-5abb7070d6e3.png)
![image](https://user-images.githubusercontent.com/69145401/188339745-bf4177f6-ac46-42d3-8a2d-192f02350b2a.png)
