### ISSUE TITLE
theme.html buttons are not working.

### ISSUE THREAD

**Issue by sukyungdev** [chingu-voyages/v40-toucans-team-10#51]
Describe the problem
The theme buttons are not working in my environment.

Expected behavior

To Reproduce

Go to 'theme.html'
Click on any theme button
See an error

Screenshots
![error](https://user-images.githubusercontent.com/96860670/188420001-4586cd9f-81ec-4f8a-9266-7dbbadfa0c8b.gif)

**Comment by genelorenzSarmiento0408** [comment]
Has this error been fixed?

**Comment by ha-anna** [comment]
I think so. @sukyungdev?
