### ISSUE TITLE
Not rendering the numbered list correctly (CSS)

### ISSUE THREAD

**Issue by genelorenzSarmiento0408** [chingu-voyages/v40-toucans-team-10#59]
**Describe the problem**
Not rendering the numbered list correctly, even though it is in the DOM

**Expected behavior**
I will see a numbered list (default CSS)

**Screenshots**
![image](https://user-images.githubusercontent.com/69145401/188781564-11e554ce-38e5-47d7-953d-9b02e319dccb.png)

**Comment by ha-anna** [comment]
Fixed!
